version: '3'
services:
  alpine-mirror-nginx:
    image: nginx:1.15.8-alpine
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/logs:/var/log
      - ./nginx/static:/usr/share/nginx/html
      - ./alpine-mirror-volume:/alpine-mirror
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
    depends_on:
      - alpine-mirror-server
    networks:
      - alpine-mirror-network
  alpine-mirror-server:
    image: kycfeel/dockerized-alpine-mirror
    build:
     context: .
     dockerfile: Dockerfile
    volumes:
      - ./alpine-mirror-volume:/alpine-mirror
    networks:
      - alpine-mirror-network

networks:
  alpine-mirror-network:
